fastq: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}_R1.fastq.gz'
cutadapt: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}_R1.cutadapt.fastq.gz'
bam: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.bam'
splice_sites: '../output/bulk-wf/rnaseq_samples/known_splice_sites.txt'
gene_lens: '../output/bulk-wf/gene_lengths.tsv'

intergenic:
  gtf: '../output/bulk-wf/intergenic.gtf'
  bed: '../output/bulk-wf/intergenic.bed'

fastqc:
  raw: '../output/bulk-wf/rnaseq_samples/{sample}/fastqc/{sample}_R1.fastq.gz_fastqc.zip'
  cutadapt: '../output/bulk-wf/rnaseq_samples/{sample}/fastqc/{sample}_R1.cutadapt.fastq.gz_fastqc.zip'
  bam: '../output/bulk-wf/rnaseq_samples/{sample}/fastqc/{sample}.cutadapt.bam_fastqc.zip'

libsizes:
        fastq:   '../output/bulk-wf/rnaseq_samples/{sample}/{sample}_R1.fastq.gz.libsize'
        cutadapt: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}_R1.cutadapt.fastq.gz.libsize'
        bam:     '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.bam.libsize'

fastq_screen: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.screen.txt'

featurecounts:
  s0: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.bam.featurecounts.s0.txt'
  s1: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.bam.featurecounts.s1.txt'
  s2: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.bam.featurecounts.s2.txt'

featurecounts_intergenic:
  s0: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.bam.featurecounts.intergenic.s0.txt'
  s1: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.bam.featurecounts.intergenic.s1.txt'
  s2: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.bam.featurecounts.intergenic.s2.txt'

libsizes_table: '../output/bulk-wf/aggregation/libsizes_table.tsv'
libsizes_yaml: '../output/bulk-wf/aggregation/libsizes_table_mqc.yaml'
rrna_percentages_table: '../output/bulk-wf/aggregation/rrna_percentages_table.tsv'
rrna_percentages_yaml: '../output/bulk-wf/aggregation/rrna_percentages_table_mqc.yaml'

rrna:
   bam: '../output/bulk-wf/rnaseq_samples/{sample}/rRNA/{sample}.cutadapt.rrna.bam'
   libsize: '../output/bulk-wf/rnaseq_samples/{sample}/rRNA/{sample}.cutadapt.rrna.bam.libsize'

multiqc: '../output/bulk-wf/aggregation/multiqc.html'

markduplicates:
   bam: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.markdups.bam'
   metrics: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.markdups.bam.metrics'

collectrnaseqmetrics:
   metrics: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.collectrnaseqmetrics.metrics'
   pdf: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.collectrnaseqmetrics.pdf'

dupradar:
   density_scatter: '../output/bulk-wf/rnaseq_samples/{sample}/dupradar/{sample}_density_scatter.png'
   expression_histogram: '../output/bulk-wf/rnaseq_samples/{sample}/dupradar/{sample}_expression_histogram.png'
   expression_boxplot: '../output/bulk-wf/rnaseq_samples/{sample}/dupradar/{sample}_expression_boxplot.png'
   expression_barplot: '../output/bulk-wf/rnaseq_samples/{sample}/dupradar/{sample}_expression_barplot.png'
   multimapping_histogram: '../output/bulk-wf/rnaseq_samples/{sample}/dupradar/{sample}_multimapping_histogram.png'
   dataframe: '../output/bulk-wf/rnaseq_samples/{sample}/dupradar/{sample}_dataframe.tsv'
   model: '../output/bulk-wf/rnaseq_samples/{sample}/dupradar/{sample}_model.txt'
   curve: '../output/bulk-wf/rnaseq_samples/{sample}/dupradar/{sample}_curve.txt'
   log: '../output/bulk-wf/rnaseq_samples/{sample}/dupradar/dupradar.log'

preseq: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}_preseq_c_curve.txt'

salmon: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.salmon/quant.sf'

rseqc:
   bam_stat: '../output/bulk-wf/rnaseq_samples/{sample}/rseqc/{sample}_bam_stat.txt'

bigwig:
   pos: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.bam.pos.bigwig'
   neg: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.bam.neg.bigwig'
   sense: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.bam.sense.bigwig'
   antisense: '../output/bulk-wf/rnaseq_samples/{sample}/{sample}.cutadapt.bam.antisense.bigwig'

downstream:
   rnaseq: 'downstream/rnaseq.html'

patterns_by_aggregate:
  merged_bigwig: '../output/bulk-wf/aggregation/merged_bigwigs/{merged_bigwig_label}.bigwig'

parquet:
  gene: '../output/bulk-wf/featurecounts.parquet'
  tpm: '../output/bulk-wf/tpm.parquet'
