fastq: 'data/rnaseq_samples/{sample}/{sample}_R1.fastq.gz'
cutadapt: 'data/rnaseq_samples/{sample}/{sample}_R1.cutadapt.fastq.gz'
bam: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.bam'
splice_sites: 'data/rnaseq_samples/known_splice_sites.txt'
intergenic:
  gtf: 'data/intergenic.gtf'
  bed: 'data/intergenic.bed'

fastqc:
  raw: 'data/rnaseq_samples/{sample}/fastqc/{sample}_R1.fastq.gz_fastqc.zip'
  cutadapt: 'data/rnaseq_samples/{sample}/fastqc/{sample}_R1.cutadapt.fastq.gz_fastqc.zip'
  bam: 'data/rnaseq_samples/{sample}/fastqc/{sample}.cutadapt.bam_fastqc.zip'

libsizes:
        fastq:   'data/rnaseq_samples/{sample}/{sample}_R1.fastq.gz.libsize'
        cutadapt: 'data/rnaseq_samples/{sample}/{sample}_R1.cutadapt.fastq.gz.libsize'
        bam:     'data/rnaseq_samples/{sample}/{sample}.cutadapt.bam.libsize'

fastq_screen: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.screen.txt'
featurecounts:
  s0: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.bam.featurecounts.s0.txt'
  s1: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.bam.featurecounts.s1.txt'
  s2: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.bam.featurecounts.s2.txt'
featurecounts_intergenic:
  s0: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.bam.featurecounts.intergenic.s0.txt'
  s1: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.bam.featurecounts.intergenic.s1.txt'
  s2: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.bam.featurecounts.intergenic.s2.txt'
libsizes_table: 'data/aggregation/libsizes_table.tsv'
libsizes_yaml: 'data/aggregation/libsizes_table_mqc.yaml'
rrna_percentages_table: 'data/aggregation/rrna_percentages_table.tsv'
rrna_percentages_yaml: 'data/aggregation/rrna_percentages_table_mqc.yaml'

rrna:
   bam: 'data/rnaseq_samples/{sample}/rRNA/{sample}.cutadapt.rrna.bam'
   libsize: 'data/rnaseq_samples/{sample}/rRNA/{sample}.cutadapt.rrna.bam.libsize'

multiqc: 'data/aggregation/multiqc.html'

markduplicates:
   bam: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.markdups.bam'
   metrics: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.markdups.bam.metrics'

collectrnaseqmetrics:
   metrics: 'data/rnaseq_samples/{sample}/{sample}.collectrnaseqmetrics.metrics'
   pdf: 'data/rnaseq_samples/{sample}/{sample}.collectrnaseqmetrics.pdf'

dupradar:
   density_scatter: 'data/rnaseq_samples/{sample}/dupradar/{sample}_density_scatter.png'
   expression_histogram: 'data/rnaseq_samples/{sample}/dupradar/{sample}_expression_histogram.png'
   expression_boxplot: 'data/rnaseq_samples/{sample}/dupradar/{sample}_expression_boxplot.png'
   expression_barplot: 'data/rnaseq_samples/{sample}/dupradar/{sample}_expression_barplot.png'
   multimapping_histogram: 'data/rnaseq_samples/{sample}/dupradar/{sample}_multimapping_histogram.png'
   dataframe: 'data/rnaseq_samples/{sample}/dupradar/{sample}_dataframe.tsv'
   model: 'data/rnaseq_samples/{sample}/dupradar/{sample}_model.txt'
   curve: 'data/rnaseq_samples/{sample}/dupradar/{sample}_curve.txt'

preseq: 'data/rnaseq_samples/{sample}/{sample}_preseq_c_curve.txt'

salmon: 'data/rnaseq_samples/{sample}/{sample}.salmon/quant.sf'

rseqc:
   bam_stat: 'data/rnaseq_samples/{sample}/rseqc/{sample}_bam_stat.txt'

bigwig:
   pos: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.bam.pos.bigwig'
   neg: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.bam.neg.bigwig'
   sense: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.bam.sense.bigwig'
   antisense: 'data/rnaseq_samples/{sample}/{sample}.cutadapt.bam.antisense.bigwig'

downstream:
   rnaseq: 'downstream/rnaseq.html'

patterns_by_aggregate:
  merged_bigwig: 'data/aggregation/merged_bigwigs/{merged_bigwig_label}.bigwig'
